plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'expo.modules.webdavclient'
version = '1.0.0'

android {
  namespace "expo.modules.webdavclient"
  defaultConfig {
    versionCode 1
    versionName "1.0.0"
  }
  lintOptions {
    abortOnError false
  }
}

dependencies {
  implementation 'com.squareup.okhttp3:okhttp:4.12.0'
}
