plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'expo.modules.smbclient'
version = '0.1.0'

android {
  namespace "expo.modules.smbclient"
  defaultConfig {
    versionCode 1
    versionName "0.1.0"
  }
  lintOptions {
    abortOnError false
  }
}

dependencies {
  implementation('eu.agno3.jcifs:jcifs-ng:2.1.10') {
    exclude group: 'org.bouncycastle', module: 'bcprov-jdk15to18'
  }
}
