plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'expo.modules.ftpserver'
version = '0.1.0'

android {
  namespace "expo.modules.ftpserver"
  defaultConfig {
    versionCode 1
    versionName "0.1.0"
  }
  lintOptions {
    abortOnError false
  }
}

dependencies {
  implementation 'org.apache.ftpserver:ftpserver-core:1.2.1'
}
