plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'expo.modules.scanmodule'
version = '1.0.0'

android {
  namespace "expo.modules.scanmodule"
  defaultConfig {
    versionCode 1
    versionName "1.0.0"
  }
  lintOptions {
    abortOnError false
  }
}

dependencies {
  implementation 'com.google.android.gms:play-services-mlkit-document-scanner:16.0.0'
  implementation 'androidx.activity:activity-ktx:1.9.0'
  implementation 'com.google.mlkit:text-recognition:16.0.1'
}
