plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'com.askfiles.mobile.sharemodule'
version = '0.7.10'

android {
  namespace "com.askfiles.mobile.sharemodule"
  defaultConfig {
    versionCode 1
    versionName "0.7.10"
  }
  lintOptions {
    abortOnError false
  }
}

dependencies {
  implementation("androidx.print:print:1.0.0")
}
